Sdp coobook fixes
Wits-SG/Demeter pull request #26
Opened 2023-09-23 19:11 UTC by Smithash

UI fixes and got refresh of cookbook to not crash but its not 100% perfect. when you refresh it goes to first recipe in the cookbook and not the current one that you refreshed on.

2023-09-23 19:14 UTC, orwellian225 requested changes
Please remove the console.logs but otherwise looks good

2023-09-23 19:14 UTC, orwellian225 commented on src/lib/components/small_recipe.svelte
> +		console.log(smallRecipeData);
Pls remove console.logs

2023-09-23 19:14 UTC, orwellian225 commented on src/routes/(app)/cookbook/[cookbook_id]/+page.svelte
> +	console.log(cookbookID);
Pls remove

2023-09-23 19:49 UTC, nihal-ranchod approved these changes
lgtm

2023-09-24 13:42 UTC, orwellian225 approved these changes
thanks, all good now

2023-09-24 15:32 UTC, merged